### ISSUE TITLE
Jquery dependences ~2.0.0 

### ISSUE THREAD

**Issue by renziito** [xuqingkuang/bootstrap-dual-select#3]
Sure that this doesn't work with Jquery up to 2.0? like 3.0^?? 

>  "jquery": "~2.0.0 

Sure that this doesn't work with : 

>  "jquery": ">=2.0.0",

I have installed jquery": "^3.3", "minimum-stability": "dev", and  when i install bootstrap-dual-select trought composer,return this : 

>  `- bower-asset/bootstrap-dual-select v0.1.2 requires bower-asset/jquery ~2.0.0 -> satisfiable by bower-asset/jquery[2.0.3, 2.0.2, 2.0.1, 2.0.0, 2.0.0-beta2, 2.0.0-beta1, 2.0.0-beta3] but these conflict with your requirements or minimum-stability.

**Comment by xuqingkuang** [comment]
Hi, the plugin was just updated for your requirement, please enjoy.
